#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
In this problem set you work with cities infobox data, audit it, come up with a
cleaning idea and then clean it up. In the first exercise we want you to audit
the datatypes that can be found in some particular fields in the dataset.
The possible types of values can be:
- NoneType if the value is a string "NULL" or an empty string ""
- list, if the value starts with "{"
- int, if the value can be cast to int
- float, if the value can be cast to float, but CANNOT be cast to int.
   For example, '3.23e+07' should be considered a float because it can be cast
   as float but int('3.23e+07') will throw a ValueError
- 'str', for all other values

The audit_file function should return a dictionary containing fieldnames and a 
SET of the types that can be found in the field. e.g.
{"field1": set([type(float()), type(int()), type(str())]),
 "field2": set([type(str())]),
  ....
}
The type() function returns a type object describing the argument given to the 
function. You can also use examples of objects to create type objects, e.g.
type(1.1) for a float: see the test function below for examples.

Note that the first three rows (after the header row) in the cities.csv file
are not actual data points. The contents of these rows should note be included
when processing data types. Be sure to include functionality in your code to
skip over or detect these rows.
"""
from collections import defaultdict
import csv
import pprint


CITIES = 'cities.csv'


     
def get_type(value): 

    try:
        int(value)
        return "Integer"
    except ValueError:
        pass
    
    try:
        float(value)
        return "float"
    except ValueError:
        pass
    
    if value == "NULL":
        return "Null"
    elif value.startswith("{"):
        return "List"
    else:      
        return "String"
   

 


# Open the CSV file
with open(CITIES, "r",encoding="utf-8") as f:
    # Create a DictReader object
    reader = csv.DictReader(f)
    header = reader.fieldnames
    fields = [field for field in header]
    columns = defaultdict(list)
    for count ,row in enumerate(reader):

        if count > 2:
            for (k,v) in row.items(): # go over each column name and value 
                columns[k].append(v)
                
    result = {}            
    for field in fields:
        types = set()
        values = columns[field]
        for value in values:
            types.add(get_type(value))
        result[field] = types  

    def convert_scientific_to_decimal(scientific_notation):
    try:
        decimal_number = float(scientific_notation)
        return decimal_number
    except ValueError:
        return None
def fix_area(area):
    if area.startswith("{"):

        # Remove the curly braces and split the string at |
        values = area.strip("{}").split("|")
        # Compare the lengths of the two values and print the longer one
        if len(values[0]) > len(values[1]):
            area = values[0]

        else:
            area = values[1]
            
        return area
    elif area == None:
        pass   
    else:
        return area        

def process_file(filename):
    # CHANGES TO THIS FUNCTION WILL BE IGNORED WHEN YOU SUBMIT THE EXERCISE
    data = []

    with open(filename, "r",encoding="utf-8") as f:
        reader = csv.DictReader(f)

        # processing file
        for count , line in enumerate(reader):
            if count > 2:
                # calling your function to fix the area value
                if "areaLand" in line:
                    
                    line["areaLand"] = convert_scientific_to_decimal(fix_area(line["areaLand"]))
                    data.append(line)

    return data
def test():
    data = process_file(CITIES)
    """
    print("Printing three example results:")
    """
    for n in range(0,2300):
        pprint.pprint(data[n]["areaLand"])
    
    assert data[3]["areaLand"] == None        
    assert data[898]["areaLand"] == 55166700.0
    assert data[1743]["areaLand"] == 14581600.0

    assert data[2274]["areaLand"] == 20564500.0


if __name__ == "__main__":
    test()
    
